version: "3.8"

services:
  nginx:
    build: ./services/nginx
    container_name: crud_nginx
    depends_on:
      - web
      - auth
      - user
      - admin
    ports:
      - "80:80"

  web:
    build: ../services/web
    container_name: crud_web
    env_file:
      - ./services/web/.env
    ports:
      - "5173:5173"

  auth:
    build: ./services/auth
    container_name: crud_auth
    env_file:
      - ./services/auth/.env
    depends_on:
      - rabbitmq
    ports:
      - "3000:80"

  user:
    build: ./services/user
    container_name: crud_user
    env_file:
      - ./services/user/.env
    depends_on:
      - rabbitmq
    ports:
      - "3001:80"

  admin:
    build: ./services/admin
    container_name: crud_admin
    env_file:
      - ./services/admin/.env
    depends_on:
      - rabbitmq
      - notification
    ports:
      - "3002:80"

  notification:
    build: ./services/notification
    container_name: crud_notification
    env_file:
      - ./services/notification/.env
    ports:
      - "3003:3003"
      - "50052:50052"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
