version: '3.8'

services:
  nginx:
    image: allajahzan/crud-micro:nginx
    container_name: crud_nginx
    depends_on:
      - web
      - auth
      - user
      - admin
    ports:
      - '80:80'

  web:
    image: allajahzan/crud-micro:web
    container_name: crud_web
    ports:
      - '5173:5173'

  auth:
    image: allajahzan/crud-micro:auth
    container_name: crud_auth
    depends_on:
     - rabbitmq      
    ports:
      - '3000:80'

  user:
    image: allajahzan/crud-micro:user
    container_name: crud_user
    depends_on:
      - rabbitmq
    ports:
      - '3001:80'

  admin:
    image: allajahzan/crud-micro:admin
    container_name: crud_admin
    depends_on:
     - rabbitmq  
     - notification    
    ports:
      - '3002:80'

  notification:
    image: allajahzan/crud-micro:notification
    container_name: crud_notification  
    ports:
      - '3003:3003'
      - '50052:50052'  

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports: 
      - '5672:5672'   
      - "15672:15672" 
