# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-cont
        image: allajahzan/crud-micro:nginx  
        imagePullPolicy: Always 

---

# service
apiVersion: v1
kind: Service
metadata:
  name: nginx-srv
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 80  # The external service port
      targetPort: 80 # The container port


