# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  labels:
    app: auth
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-cont
        image: allajahzan/crud-micro:auth  
        imagePullPolicy: Always
        envFrom:
            - configMapRef:
                name: env-auth-config

---

# service
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000  # The external service port
      targetPort: 3000 # The container port


