# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification-cont
          image: allajahzan/crud-micro:notification
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-notification-config

---
# service
apiVersion: v1
kind: Service
metadata:
  name: notification-srv
spec:
  type: NodePort
  selector:
    app: notification
  ports:
    - name: notification
      protocol: TCP
      port: 3003
      targetPort: 3003
    - name: gRPC
      protocol: TCP
      port: 50052 # The external service port
      targetPort: 50052 # The container port

