# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-cont
          image: allajahzan/crud-micro:user
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env-user-config

---
# service
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3001 # The external service port
      targetPort: 3001 # The container port

